version: '3'
services:
    api:
        build:
            context: "../api"
            dockerfile: Dockerfile
        ports:
          - 8080:8080
        networks:
          - frontend
    ui:
        build:
            context: "../ui"
            dockerfile: Dockerfile
        ports:
          - 80:80
    keycloak:
        build:
            context: "../keycloak"
            dockerfile: Dockerfile
        ports:
          - 9080:9080
        networks:
          - frontend

networks:
    frontend:
